apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  labels:
    run: jersey-services
  name: jersey-services
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  selector:
    matchLabels:
      run: jersey-services
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: jersey-services
    spec:
      containers:
      - image: sspanchal/jersey.30003
        imagePullPolicy: Always
        name: jersey-services
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        worker: jersey-worker
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: jersey-services
  name: jersey-services
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30003
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: jersey-services
  sessionAffinity: None
  type: NodePort

